language: generic
os: osx
osx_image: xcode10.2
if: type != pull_request
install:
- curl -o Unity.pkg https://download.unity3d.com/download_unity/de9eb5ca33c5/MacEditorInstaller/Unity-2017.4.7f1.pkg
- sudo installer -dumplog -package Unity.pkg -target /
script:
- /Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode -nographics -silent-crashes -projectPath ./stroke/ -runEditorTests -quit
